### ISSUE TITLE
Attribute Error when running demo

### ISSUE THREAD

**Issue by kangah-codes** [forslund/pyParallax#5]
Running the `demo.py` file throws the error AttributeError: module 'parallax' has no attribute 'ParallaxSurface'

**Full Traceback**
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    bg = parallax.ParallaxSurface((640, 480), pygame.RLEACCEL)
AttributeError: module 'parallax' has no attribute 'ParallaxSurface'

**Comment by forslund** [comment]
Sorry for not replying here in forever, I'll look into it tonight.

**Comment by williamu32** [comment]
Edit the file __init__.py:

`from .parallax import *`

***Nice***

**Comment by forslund** [comment]
Thanks @williamu32 for flagging this. I've done some minor updates including this change.

**Comment by forslund** [comment]
This should be fixed. closing the issue
