### ISSUE TITLE
Add brief explanation to README on making a layer that doesn't scroll

### ISSUE THREAD

**Issue by cheffley6** [forslund/pyParallax#7]
**Is your feature request related to a problem? Please describe.**
Explained in my PR [here.](https://github.com/forslund/pyParallax/pull/6)

**Describe the solution you'd like**
Update README. Check it out [here.](https://github.com/forslund/pyParallax/pull/6)

**Describe alternatives you've considered**

**Additional context**

**Comment by forslund** [comment]
Resolved by #6. Closing issue
